name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      working-directory: test
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: test
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30